In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('train.csv')

In [3]:
df.shape

(404290, 6)

In [4]:
df.sample(5)

,id,qid1,qid2,question1,question2,is_duplicate
65598,65598,113811,113812,How would I combine block printing into two fo...,What are some private chat sites in India?,0
5172,5172,10190,10191,Why do people adopt savannah cats?,Why is my adopted cat hiding from me?,0
169022,169022,261671,261672,How many people use Google Suggest?,How many people use Google?,0
217017,217017,55988,323279,What is the salary for new graduates starting ...,"At Facebook and Google, why are many new CS gr...",0
71082,71082,122383,122384,What are the most important periods in history?,I am in class 9 and have done mathematics chap...,0

In [5]:
new_df = df.sample(30000)

In [6]:

new_df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [7]:
new_df.duplicated().sum()

np.int64(0)

In [8]:
ques_df = new_df[['question1','question2']]
ques_df.head()

,question1,question2
171836,What is the difference between a square and a ...,How to prove that a number isn't a perfect squ...
6325,Can I get some survey results and stats of Ind...,Can I get some survey results and stats of Ind...
144892,Does tea tree oil really prevent acne?,Does tea tree oil really help get rid of acne ...
319462,Why do people use slang?,Why do people use slangs in life?
20409,What is the best beginner coding language?,Which coding language is best to start with?

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
# merge texts
questions = list(ques_df['question1']) + list(ques_df['question2'])

cv = CountVectorizer(max_features=3000)
q1_arr, q2_arr = np.vsplit(cv.fit_transform(questions).toarray(),2)

In [10]:
temp_df1 = pd.DataFrame(q1_arr, index= ques_df.index)
temp_df2 = pd.DataFrame(q2_arr, index= ques_df.index)
temp_df = pd.concat([temp_df1, temp_df2], axis=1)
temp_df.shape

(30000, 6000)

In [11]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
171836,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6325,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
144892,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
319462,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20409,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355649,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
363165,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2169,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55332,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
122015,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:

temp_df['is_duplicate'] = new_df['is_duplicate']

In [13]:
temp_df.head()

,0,1,2,3,4,5,6,7,8,9,...,2991,2992,2993,2994,2995,2996,2997,2998,2999,is_duplicate
171836,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6325,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
144892,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
319462,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
20409,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(temp_df.iloc[:,0:-1].values,temp_df.iloc[:,-1].values,test_size=0.2,random_state=1)

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier(n_jobs=True)
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7348333333333333

In [17]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train,y_train)
y_pred = xgb.predict(X_test)
accuracy_score(y_test,y_pred)

0.7241666666666666